@Service_HostAddress = https://localhost:7801

GET {{Service_HostAddress}}/api/discovery

###

GET {{Service_HostAddress}}/api/discovery/Example.Service

###

POST {{Service_HostAddress}}/api/discovery/init

###
