@Service_HostAddress = https://localhost:7001

GET {{Service_HostAddress}}/hc

###

GET {{Service_HostAddress}}/api/info

###

POST {{Service_HostAddress}}/api/info/register

###

POST {{Service_HostAddress}}/api/info/disable

###

POST {{Service_HostAddress}}/api/info/disable?notifyDiscovery=true

###

POST {{Service_HostAddress}}/api/info/enable

###

POST {{Service_HostAddress}}/api/info/enable?notifyDiscovery=true

###
